function ah = visualize_signals(source_coords, measurement_coords);

	[x,y,z] = sphere;
	fh = figure();
	ah = axes('parent',fh);
	half_head = ceil(size(x,1)/2);
	s = surf(ah, x(half_head:end,:), y(half_head:end,:),...
	 z(half_head:end,:));
	s.FaceAlpha = .1;
	s.FaceColor = [.8 .5 1];

	lh(1) = line('Xdata', source_coords(:,1),...
	 'Ydata', source_coords(:,2),...
	 'Zdata', source_coords(:,3), 'linestyle', 'none', 'marker', '*',...
	 'parent', ah);
	lh(2) = line('Xdata', measurement_coords(:,1),...
       	 'Ydata', measurement_coords(:,2),...
	 'Zdata', measurement_coords(:,3), 'linestyle', 'none',...
	 'linewidth', 1, 'marker', 'o', 'markersize', 5,...
	 'markerfacecolor', 'k', 'parent', ah);
	legend([lh(1) lh(2)],'sources','measurement locations');
end
